version: "3"

services:
  app:
    build:
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    networks:
      - node-net
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    command: --innodb-use-native-aio=0
    ports: 
      - 3306:3306
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - node-net

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
    restart: always
    networks:
      - node-net


networks:
  node-net:
    driver: bridge